package com.thebizio.commonmodule.enums;

public enum WebhookEventType {

    INVOICE_PAYMENT_FAILED,
    INVOICE_PAID,
    PAYMENT_METHOD_ATTACHED,
    CUSTOMER_RESOURCE_CREATED,
    SETUP_INTENT_CREATED,
    SETUP_INTENT_SUCCEEDED,
    UNKNOWN,
    PAYMENT_INTENT_SUCCEEDED
}
