ALTER TABLE users DROP COLUMN IF EXISTS middle_name;

ALTER TABLE organizations
DROP COLUMN IF EXISTS description,
DROP COLUMN IF EXISTS industry,
DROP COLUMN IF EXISTS className,
DROP COLUMN IF EXISTS structure,
DROP COLUMN IF EXISTS industryType,
DROP COLUMN IF EXISTS exchange,
DROP COLUMN IF EXISTS market,
DROP COLUMN IF EXISTS symbol,
DROP COLUMN IF EXISTS shortName,
DROP COLUMN IF EXISTS otherName,
ADD COLUMN IF NOT EXISTS subdomain VARCHAR(255),
ADD COLUMN IF NOT EXISTS type_of_business VARCHAR(255),
ADD COLUMN IF NOT EXISTS billing_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS signup_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS tax_id VARCHAR(255);
